export enum UserRole {
  HOUSEHOLD = 'HOUSEHOLD',
  COLLECTOR = 'COLLECTOR',
  RAGPICKER = 'RAGPICKER',
  KABADIWALA = 'KABADIWALA',
  RECYCLER = 'RECYCLER',
  ADMIN = 'ADMIN',
}

export enum MaterialType {
  PET_PLASTIC = 'PET_PLASTIC',
  HDPE_PLASTIC = 'HDPE_PLASTIC',
  MIXED_PLASTIC = 'MIXED_PLASTIC',
  PAPER = 'PAPER',
  CARDBOARD = 'CARDBOARD',
  METAL_FERROUS = 'METAL_FERROUS',
  METAL_NON_FERROUS = 'METAL_NON_FERROUS',
  GLASS = 'GLASS',
  E_WASTE = 'E_WASTE',
  ORGANIC = 'ORGANIC',
  MIXED = 'MIXED',
}

export enum BatchStatus {
  CREATED = 'CREATED',
  COLLECTED = 'COLLECTED',
  IN_TRANSIT = 'IN_TRANSIT',
  AT_AGGREGATOR = 'AT_AGGREGATOR',
  GRADED = 'GRADED',
  DISPATCHED = 'DISPATCHED',
  RECEIVED_BY_RECYCLER = 'RECEIVED_BY_RECYCLER',
  RECYCLED = 'RECYCLED',
}

export enum CustodyEventType {
  CREATED = 'CREATED',
  PICKUP = 'PICKUP',
  HANDOFF = 'HANDOFF',
  WEIGHT_UPDATE = 'WEIGHT_UPDATE',
  QUALITY_GRADED = 'QUALITY_GRADED',
  DISPATCHED = 'DISPATCHED',
  RECEIVED = 'RECEIVED',
  RECYCLED = 'RECYCLED',
  LOCATION_UPDATE = 'LOCATION_UPDATE',
}

export enum QualityGrade {
  A = 'A',
  B = 'B',
  C = 'C',
  CONTAMINATED = 'CONTAMINATED',
}

export enum JobStatus {
  WAITING = 'WAITING',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum LanguageCode {
  EN = 'en',
  HI = 'hi',
  TA = 'ta',
  BN = 'bn',
}
